# Essential services for AppFlowy Cloud

version: "3.7"
services:
  redis:
    restart: on-failure
    image: redis
    ports:
      - 6379:6379

  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: recast:latest
    depends_on:
      - redis
    ports:
      - "8080-8081:8080"
    environment:
      - RUST_LOG=info
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    restart: on-failure
    image: nginx
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
  minio_data:
